const DEFAULT_FPS = 30;
const DEFAULT_MEDIA_DURATION = 5;
const DEFAULT_TEXT_DURATION = 3;

const DEFAULT_API_URL = "http://localhost:5000";

const DEFAULT_LANGUAGE = "en";
const SUPPORTED_LANGUAGES = ["en", "vi"];

export {
	DEFAULT_FPS,
	DEFAULT_MEDIA_DURATION,
	DEFAULT_TEXT_DURATION,
	DEFAULT_API_URL,
	DEFAULT_LANGUAGE,
	SUPPORTED_LANGUAGES,
};
